image: python:latest

stages:
  - linting
  - test

linting-job:
  stage: linting
  before_script:
    - pip install flake8
    - pip install black
  script:
    - flake8 .
    - black --check .

test-job:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" || $CI_COMMIT_BRANCH == "dev"
  before_script:
    - echo "Installing requirements..."
    - pip install -r requirements-dev.txt
  script:
    - echo "Running tests..."
    - python3 -m pytest tests/

enable_merge:
  only: [merge_requests]
  script:
    - echo true
