image: python:latest

stages:          # List of stages for jobs, and their order of execution
  - test

test-job:   # This job runs in the test stage.
  stage: test
  before_script:
    - echo "Installing requirements..."  
    - pip install -r requirements.txt
  script:
    - echo "Running tests..."
    - python3 -m pytest tests/
