image: python:latest

before_script:
  - pip install flake8
  - pip install pyproject-flake8
  - pip install black
  - echo "Installing requirements..."
  - pip install -r requirements-dev.txt

stages:
  - linting&tests

flake8-job:
  stage: linting&tests
  rules:
    - when: always
  script:
    - echo "Running flake8..."
    - pflake8 .

black-job:
  stage: linting&tests
  rules:
    - when: always
  script:
    - echo "Running black..."
    - black --check .

test-job:
  stage: linting&tests
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" || $CI_COMMIT_BRANCH == "dev"
  script:
    - echo "Running tests..."
    - python3 -m pytest tests/
