image: python:latest

stages:
  - linting&tests

linting&test-job:
  stage: linting&tests

  before_script:
    - pip install flake8
    - pip install pyproject-flake8
    - pip install black
    - echo "Installing requirements..."
    - pip install -r requirements-dev.txt

  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" || $CI_COMMIT_BRANCH == "dev"

  script:
    - pflake8 .
    - black --check .
    - echo "Running tests..."
    - python3 -m pytest tests/
