version: "3"

volumes:
  postgres_data:

services:
  db:
    container_name: viewger_postgres
    image: postgres:latest
    restart: always
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 5

  app:
    container_name: viewger_app
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: ["sh", "docker-entrypoint.sh"]
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_PORT}
