volumes:
  postgres_data:

services:
  db:
    container_name: viewger_postgres
    image: postgres:latest
    ports:
      - 35432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 5

  app:
    container_name: viewger_app
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: ["sh", "docker-entrypoint.sh"]
    ports:
      - 8888:8888
    environment:
      DATABASE_URL: ${DATABASE_URL}