version: "3"

volumes:
  postgres_data:

services:
  db:
    container_name: viewger_postgres
    image: postgres:latest
    restart: always
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  app:
    container_name: viewger_app
    build: .
    depends_on:
      - db
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
