[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
skip-string-normalization = true
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.env
)/
'''

[tool.flake8]
exclude = '''
/(
    */migrations/
    | venv/
    | env/
)/
'''
max-line-length = 120
max-complexity = 10
