"""init pull request

Revision ID: 022d8a4da8d7
Revises: 39086f7fbd4e
Create Date: 2022-04-19 14:22:29.853402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022d8a4da8d7'
down_revision = '39086f7fbd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_task_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request')
    # ### end Alembic commands ###
