"""project description nullable

Revision ID: 25aa8a2fedb9
Revises: 70719ad046e5
Create Date: 2022-05-16 14:48:51.865951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25aa8a2fedb9'
down_revision = '70719ad046e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'description', existing_type=sa.VARCHAR(length=512), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'description', existing_type=sa.VARCHAR(length=512), nullable=False)
    # ### end Alembic commands ###
