"""init pr_skill

Revision ID: 2927aee8910d
Revises: 0c970b1a696b
Create Date: 2022-04-18 23:24:40.470477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2927aee8910d'
down_revision = '0c970b1a696b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_skill',
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_pr_skill_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_pr_skill_skill_id_skill')),
    sa.PrimaryKeyConstraint('pr_id', name=op.f('pk_pr_skill'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_skill')
    # ### end Alembic commands ###
