"""init UserSkill

Revision ID: 2937175aad49
Revises: f106874f67eb
Create Date: 2022-04-19 14:36:57.524614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2937175aad49'
down_revision = 'f106874f67eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_user_skill_skill_id_skill')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skill_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skill'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skill')
    # ### end Alembic commands ###
