"""init review

Revision ID: 42e2a89f1537
Revises: 022d8a4da8d7
Create Date: 2022-04-19 14:25:55.087377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42e2a89f1537'
down_revision = '022d8a4da8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('upd_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', postgresql.ENUM(name='review_status'), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_review_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.add_column('pull_request', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_pull_request_author_id_users'), 'pull_request', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pull_request_author_id_users'), 'pull_request', type_='foreignkey')
    op.drop_column('pull_request', 'author_id')
    op.drop_table('review')
    # ### end Alembic commands ###