"""init review

Revision ID: 42e3684ca9bf
Revises: 07b63e80ad41
Create Date: 2022-04-20 13:19:09.281447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e3684ca9bf'
down_revision = '07b63e80ad41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('upd_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum(name='statuses'), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_review_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
