"""init reviews

Revision ID: 4981b3747a43
Revises: 56555fe32197
Create Date: 2022-04-18 22:01:01.217124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4981b3747a43'
down_revision = '56555fe32197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('upd_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', postgresql.ENUM(name='review_status'), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_review_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###