"""init pull request module

Revision ID: 56555fe32197
Revises: 8d296729bd1f
Create Date: 2022-04-18 21:15:07.399767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56555fe32197'
down_revision = '8d296729bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_task_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_pull_request_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request')
    # ### end Alembic commands ###