"""init members

Revision ID: 57bcefa043ce
Revises: 27bdf038d6a3
Create Date: 2022-04-18 23:13:30.266486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57bcefa043ce'
down_revision = '27bdf038d6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', postgresql.ENUM(name='role'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_member_project_id_project')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_member_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_member'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
