"""init skill

Revision ID: 63db30bf0410
Revises: 27cb6fa450c2
Create Date: 2022-04-19 14:32:01.697482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63db30bf0410'
down_revision = '27cb6fa450c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill')),
    sa.UniqueConstraint('code', name=op.f('uq_skill_code')),
    sa.UniqueConstraint('name', name=op.f('uq_skill_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    # ### end Alembic commands ###
