"""init user_skill

Revision ID: 70719ad046e5
Revises: bfd48b6dca21
Create Date: 2022-04-20 13:21:44.684081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70719ad046e5'
down_revision = 'bfd48b6dca21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_skill',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_user_skill_skill_id_skill')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skill_user_id_users')),
        sa.PrimaryKeyConstraint('user_id', 'skill_id', name=op.f('pk_user_skill')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skill')
    # ### end Alembic commands ###
