"""init member

Revision ID: b81844e2357e
Revises: af0d84abfe17
Create Date: 2022-04-20 13:16:00.740488

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b81844e2357e'
down_revision = 'af0d84abfe17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum(name='roles'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_member_project_id_project')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_member_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
