"""init PRSkill

Revision ID: f106874f67eb
Revises: d48df208a9b5
Create Date: 2022-04-19 14:35:20.062565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f106874f67eb'
down_revision = 'd48df208a9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_pr_skill_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_pr_skill_skill_id_skill')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pr_skill'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_skill')
    # ### end Alembic commands ###