"""init pr_skill

Revision ID: f60db7f97553
Revises: 63db30bf0410
Create Date: 2022-04-19 15:16:22.594697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60db7f97553'
down_revision = '63db30bf0410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_skill',
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name=op.f('fk_pr_skill_pr_id_pull_request')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_pr_skill_skill_id_skill')),
    sa.PrimaryKeyConstraint('pr_id', name=op.f('pk_pr_skill'))
    )
    op.add_column('pull_request', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_pull_request_project_id_project'), 'pull_request', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pull_request_project_id_project'), 'pull_request', type_='foreignkey')
    op.drop_column('pull_request', 'project_id')
    op.drop_table('pr_skill')
    # ### end Alembic commands ###
