name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install -r requirements.txt
          pip install isort flake8
          ls -la
          isort . --check
          flake8 . --max-line-length=120
          python3 -m pytest tests/
