name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: run tests
    container: python:3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install -r requirements.txt
          pip install pytest
          python3 -m pytest tests/

      - name: run isort
        run: |
          pip install isort
          ls -la
          isort . --check

      -name: run flake8
        run: |
          pip install flake8
          ls -la
          






